In [5]:
def sum(a,b,c,d,e,f):
    return a+b+c+d+e+f
sum(5,8,2,4,7,9)

35

In [7]:
def multiply(a,b,c,d,e):
    return a*b*c*d*e
multiply(4,3,5,6,2)

720

In [48]:
import numpy as np

array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

#a) Sort the flattened array
sort=np.sort(array_hw, axis=None)
print(sort)

#b) Sort the second column
sort_col=np.sort(array_hw[...,1])
print(sort_col)

#c) Sort the third row
sort_row=np.sort(array_hw[2,...])
print(sort_row)

#d) Extract the second row onwards
extract_rows=array_hw[1:,...]
print(extract_rows)

#e) Extract the third column onwards
extract_cols=array_hw[..., 2:]
print(extract_cols)

#f) obtain the square of array_hw
arr_sqrd=np.square(array_hw)
print(arr_sqrd)

#g)Slice the element from the third row and fourth column position 3X4
extract_element=array_hw[2, 3]
print(extract_element)

#f) obtain the total sum of array_hw
arr_sum=array_hw.sum()
print(arr_sum)

#h) How many dimentions does array_hw have?
arr_dim=array_hw.ndim
print(arr_dim)

#i) What is the data type listed in array_hw?
arr_type=array_hw.dtype
print(arr_type)

#j) What is the size of the memory in bytes consumed by all the elements in array_hw?
arr_memory=array_hw.nbytes
print(arr_memory)


[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]
[5 7 7 9]
[2 4 6 7 8 8]
[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]
[[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]
4
145
2
int64
192
